language: python            # this works for Linux but is an error on macOS or Windows

python:
    - 3.6
    - 3.7

jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH


install: 
    - pip install -r requirements.txt 
    - pip install .
          
script: 
    travis_wait 30 mvn pytest --disable-warnings -r A --maxfail=10


# require the branch name to be master (note for PRs this is the base branch name)
notifications:
  slack:
    if: branch = master
    slack:
    on_success: change
    on_failure: change
